CREATE TABLE nodes (
  id SERIAL PRIMARY KEY,
  nid UUID NOT NULL UNIQUE,
  mac VARCHAR(17) NOT NULL UNIQUE,
  name VARCHAR(128) NOT NULL,
  notes VARCHAR(256),
  locations_id INTEGER,
  applications_ids INTEGER[],
  ts TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE nodes_status (
  id SERIAL PRIMARY KEY,
  nodes_id INTEGER NOT NULL UNIQUE,
  nid UUID NOT NULL UNIQUE,
  ip VARCHAR(15),
  status INTEGER DEFAULT -1,
  ts TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE applications (
  id SERIAL PRIMARY KEY,
  name VARCHAR(128) NOT NULL UNIQUE,
  notes VARCHAR(256),
  typ VARCHAR(4) NOT NULL,
  ts TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE locations (
  id SERIAL PRIMARY KEY,
  name VARCHAR(128) NOT NULL UNIQUE,
  notes VARCHAR(256),
  lat FLOAT8,
  long FLOAT8
);